### ISSUE TITLE
Create a slackbot to help moderate dialogue

### ISSUE THREAD

**Issue by hrod** [drupaldiversity/administration#38] opened 2017-03-30 17:30 UTC
Slackbots can be used for a variety of tasks when certain flagged words are used. For example, if someone uses a word that is derogatory, we can have a Slackbot fire to say something like "Reminder: Please keep dialogue civil." If someone uses the phrase, "Check your privilege", we can fire a link to a definition so that other people understand what that connotes.  We would need a list of phrases/words that could trigger actions, so please feel free to add your suggestion to this issue.

**Comment by AlannaBurke** [comment] 2017-03-30 19:23
we could probably have a slackbot to take commands for definitions that we create, to help with explanations, as well.

**Comment by rubyji** [comment] 2017-03-30 20:08
If it's not possible to trigger the bot when people join the channel, we could trigger it by using a phrase like "Welcome to DD&I!"

**Comment by AlannaBurke** [comment] 2017-03-30 20:19
There are literally millions of ways we could do this. I like the idea of a welcome bot, to start. We could easily do something like this: https://medium.com/@izzydoesizzy/create-a-slack-bot-that-privately-greets-new-users-in-5-easy-steps-a38eabeabcb5

**Comment by sugaroverflow** [comment] 2017-03-31 21:21
I like both ideas! Especially the welcome bot! @AlannaBurke

We can give them some helpful links to our participation policies and some tips for how to engage in the channel :)

**Comment by rubyji** [comment] 2017-03-31 21:32
Keep in mind that that because we are on a free Slack account there is a
limit on the number of bots and I think Drupal has already reached the
limit.

**Comment by mlhess** [comment] 2017-04-03 14:00
@rubyji I can confirm the drupal slack has hit the limit.

**Comment by mglaman** [comment] 2017-04-03 19:35
>  If someone uses the phrase, "Check your privilege", we can fire a link to a definition so that other people understand what that connotes.

I have no idea the context that this would require someone to respond flat out with *Check your privilege.* I would _love_ to know what circumstances return this direct of a remark. You're going to make people not involved in this inner circle feel ostracized and weary of "exerting their privilege."

**Comment by AlannaBurke** [comment] 2017-04-03 19:42
I'm pretty sure that was an example. I don't recall someone using that exact phrase, but there have been several conversations over the definition of "privilege" and other terms.

**Comment by mglaman** [comment] 2017-04-03 19:43
Also, I was made aware this is just for the DDI Slack channel, it sounded like an effort by the group for other project communication channels.

I'm all for bots to help moderate. Just the example comes off a bit offsetting.

EDIT:

>  I don't recall someone using that exact phrase, but there have been several conversations over the definition of "privilege" and other terms.

It's in the summary, which is why I brought it up.

**Comment by AlannaBurke** [comment] 2017-04-03 20:05
If there are other channels and moderators who want to work together, that's great! Right now, the DD&I channel is in great need of moderation. 

I read the issue. I meant that I did not recall someone using that phrase in the channel. I'm not sure how often you are in the channel, but as I said, there have been several repetitive and exhausting conversations about definitions of terms, either because someone didn't understand a concept, or said something offensive and wasn't aware, which is why we suggested this idea.

**Comment by mglaman** [comment] 2017-04-03 20:35
Okay, wow. So I totally took this the _opposite_ way. You're saying it can be a factoid or definition. "Okay, here is what Check Your Privilege means". Not necessarily telling someone "hey, cool it."

I got that connotation because it followed the "hey, try not swearing" example. That's where my confusion came from. It didn't seem as a "Here you go, this is what it means" but more of a "Better check yourself"

**Comment by rubyji** [comment] 2017-04-03 21:01
If it helps you get back on track no-one in the DD&I channel has ever said anything remotely like "check your privilege." But in discussion, especially about inclusion, the topic of of privilege has arisen and certain people (who frankly are probably not earnestly participating in our working group) have challenged the whole notion of privilege or the assertion that it has anything to do with what we're doing. 

We're in a place where an increasing number of people are concerned about diversity but we all have varying levels of knowledge about it and experience working on it (plus different languages!). So the idea is to help people get caught up so we can have good conversations without going in circles. 

There are also issues on creating a primer or glossary for people #37 , creating training resources #40 , and also our existing list of links on this subject https://drupaldiversity.github.io/resources/.

**Comment by mglaman** [comment] 2017-04-03 21:10
> have challenged the whole notion of privilege 

And I don't want to come off this way because I'm aware there is privilege. However, I have seen a lot of actions? communication? Not sure right wording, but it comes off as aggressive and causes an opposite effect.

I wanted to speak up, as chances are I may not have been the only one who read and raised an eyebrow. Thanks for all the clarifications.

**Comment by hrod** [comment] 2017-04-03 22:33
@mglaman I will respond since it's me that originally wrote that sentence:

> You're saying it can be a factoid or definition. "Okay, here is what Check Your Privilege means". Not necessarily telling someone "hey, cool it."

Yep :) My idea was to ensure we're all on the same page about language and common concepts that you may hear around the web so people don't have to keep repeating themselves or hash out the same dialogues.

**Comment by mglaman** [comment] 2017-04-03 22:51
Sounds great, and all for it. I know I could use it :)

**Comment by rachellawson** [comment] 2017-04-13 07:02
DD&I is a human subject that needs handling in a human way, adjusted to the person we are talking with at the time. Using a bot in this scenario is almost certainly going to fail to create the right feelings and response in the recipient of whatever message is posted. 
Please don't do this - it will not have the effect you think it will have

**Comment by YesCT** [comment] 2017-05-02 13:55
https://github.com/drupaldiversity/administration/issues/34 (#diversity-inclusion channel moderation team)

**Comment by YesCT** [comment] 2017-05-02 13:57
from #34 

> Create and use slackbot responses when appropriate. https://drupal.slack.com/customize/slackbot Consider making them short and convenient to type while unique enough they will not be automatically triggered when not intended, for example: preface with ! like "!ddi stay on topic", "!ddi guidelines", etc.

**Comment by sugaroverflow** [comment] 2017-07-16 16:59
Closing this because we have a moderation team and guidelines being set up and I think that the general consensus is against using a bot for moderation which could have sensitive situations.

**Closed as completed by sugaroverflow** 2017-07-16 16:59 UTC
Labels: Moderation
